#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
===============================================================================
PLEF V2 -- SCRIPT 09 : RELEASE ASSEMBLY AND PROVENANCE VERIFICATION
                       (v09.1.0)
===============================================================================

WHAT THIS SCRIPT IS FOR (plain language)
----------------------------------------
The manuscript asserts that a dozen external artifacts exist: input manifests
with checksums, a timestamped decision file, annotation responses for all four
rounds including the two that were rejected, integrity-check code, an
environment lock, and the raw outputs behind every table and figure. A PDF is
not evidence that any of those exist. This script assembles them into one
release directory, writes a checksum manifest over everything it collected,
and FAILS if a claimed artifact is missing.

The point is not packaging. The point is that a reviewer should be able to
verify each provenance claim rather than take it on trust, and that you should
find out now if something the manuscript promises is not on disk.

STAGES
------
  S1  Collect the nine artifact classes named in the supplementary material.
  S2  Write requirements-lock.txt from the live interpreter, so the stated
      environment is the one that actually ran.
  S3  Checksum every collected file (SHA-256) into MANIFEST-RELEASE.txt.
  S4  Verify each provenance claim the manuscript makes against what was
      actually collected. Any unmet claim is an error, not a warning.
  S5  Write the repository README and a LICENSE placeholder.

WHAT IT WILL NOT DO
-------------------
It will not invent an artifact. If the decision file is absent, it says so and
exits non-zero; it does not write a substitute. If a claim in the manuscript
has no artifact behind it, the correct fix is to remove the claim or produce
the artifact, and this script tells you which claims are in that state.

OUTPUT
------
  release/            the directory to publish
  release/MANIFEST-RELEASE.txt
  release/README.md
  results/forensics/console_log_09.txt

EXIT CODES
----------
  0 every claimed artifact present and checksummed
  2 missing prerequisite
  3 one or more provenance claims unmet -- DO NOT SUBMIT
===============================================================================
"""

import argparse
import datetime
import hashlib
import json
import os
import shutil
import subprocess
import sys
import traceback
from pathlib import Path

SCRIPT_VERSION = "09.4.0"

# Each entry: (label, source glob relative to root, destination subdir,
#              required, the manuscript sentence it supports)
ARTIFACTS = [
    ("input manifests + checksums", "MANIFEST/*.json", "manifest", True,
     "input manifests with SHA-256 checksums for every source file"),
    ("decision file", "DECISIONS.md", ".", True,
     "26 declarations, each machine-timestamped before the corresponding output"),
    ("annotation responses", "data/interim/annotations/annotations_rater*.csv",
     "annotation", True,
     "annotation response files for all rounds, including rejected rounds"),
    ("rejected rounds", "data/interim/annotations/round*/*.csv",
     "annotation/rejected", False,
     "the two rejected annotation rounds are released"),
    ("gold file", "data/interim/annotations/gold*.csv", "annotation", False,
     "the human criterion used for the preliminary comparison"),
    ("annotation guide", "data/interim/annotations/**/*GUIDE*.md",
     "annotation", False, "the annotation protocol given to annotators"),
    ("scored outputs", "results/canonical/scored_*.csv", "scored", True,
     "the raw numerical outputs from which every table and figure is generated"),
    ("shard markers", "results/canonical/scored_*.done", "scored", True,
     "per-shard row counts and content hashes"),
    ("result tables", "results/tables/*.csv", "tables", True,
     "every table in the manuscript, machine-readable"),
    ("all results json", "results/tables/all_results.json", "tables", True,
     "the complete result object"),
    ("audit reconciliation", "results/AUDIT_RECONCILIATION.md", ".", True,
     "the reconciliation of every disputed quantity"),
    ("null analysis report", "results/NULLS.md", ".", True,
     "the null distributions, their generating parameters and empirical p-values"),
    ("null draws", "results/tables/null_draws.csv", "tables", True,
     "the actual simulated draws behind Figure 3 and Table 7"),
    ("figures", "results/figures/*.png", "figures", False,
     "figures generated by the released scripts"),
    ("console logs", "results/forensics/console_log*.txt", "logs", True,
     "the run log for every pipeline stage"),
    ("forensic report", "results/forensics/*.md", "logs", False,
     "the initial forensic audit"),
    ("framework core", "src/plef_core.py", "src", True,
     "the framework core, standard-library only"),
    ("lexicons", "src/plef_lexicons.json", "src", True,
     "the lexicons, lifted verbatim from the original implementation"),
    ("baseline adapter", "src/plef_baselines.py", "src", True,
     "reference baseline implementations behind one interface"),
    ("purity test", "src/plef_purity.py", "src", True,
     "the test that verifies the core imports with third-party packages blocked"),
]

# Manuscript claims that must be backed by a collected artifact.
CLAIMS = [
    ("input manifests with SHA-256 checksums", ["input manifests + checksums"]),
    ("timestamped decision file", ["decision file"]),
    ("annotation responses for all rounds", ["annotation responses"]),
    ("integrity-check code", ["integrity-check code"]),
    ("dataset filtering logs", ["console logs"]),
    ("deduplication report", ["audit reconciliation"]),
    ("null distributions and p-values", ["null analysis report", "null draws"]),
    ("environment lock file", ["environment lock"]),
    ("raw outputs behind every table", ["scored outputs", "result tables"]),
    ("script generating each figure", ["analysis scripts"]),
    ("standard-library-only core verified by a test", ["framework core", "purity test"]),
]


class Tee:
    def __init__(self, path):
        Path(path).parent.mkdir(parents=True, exist_ok=True)
        self.f = open(path, "w", encoding="utf-8")
        self.stdout = sys.stdout
    def write(self, s):
        try: self.stdout.write(s)
        except UnicodeEncodeError:
            self.stdout.write(s.encode("ascii", "replace").decode("ascii"))
        self.f.write(s)
    def flush(self): self.stdout.flush(); self.f.flush()
    def close(self):
        try: self.f.close()
        except Exception: pass


def rule(ch="-", w=80): print(ch * w)
def head(t): print(); rule("="); print(t); rule("=")
def sub(t): print(); print(t); rule("-")


def sha256(p):
    h = hashlib.sha256()
    with open(p, "rb") as f:
        for b in iter(lambda: f.read(1 << 20), b""):
            h.update(b)
    return h.hexdigest()


def main():
    ap = argparse.ArgumentParser(description="PLEF V2 script 09 -- release assembly.")
    ap.add_argument("--root", required=True)
    ap.add_argument("--scripts", default="",
                    help="directory holding the pipeline scripts "
                         "(default: the parent of --root)")
    ap.add_argument("--out", default="", help="release directory (default: <root>/release)")
    args = ap.parse_args()
    root = Path(args.root)
    scripts = Path(args.scripts) if args.scripts else root.parent
    out = Path(args.out) if args.out else root / "release"
    if not root.exists():
        print(f"FATAL: {root} does not exist")
        return 2

    tee = Tee(root / "results" / "forensics" / "console_log_09.txt")
    sys.stdout = tee
    try:
        head("PLEF V2 -- SCRIPT 09 : RELEASE ASSEMBLY")
        print(f"  script version : {SCRIPT_VERSION}")
        print(f"  started        : {datetime.datetime.now().isoformat(timespec='seconds')}")
        print(f"  root           : {root}")
        print(f"  scripts        : {scripts}")
        print(f"  release        : {out}")

        if out.exists():
            shutil.rmtree(out)
        out.mkdir(parents=True)

        # ---- S1 artifacts ------------------------------------------------
        sub("S1  COLLECT ARTIFACTS")
        collected, missing = {}, []
        for label, pat, dest, required, claim in ARTIFACTS:
            files = sorted(root.glob(pat))
            files = [f for f in files if f.is_file()]
            if not files:
                mark = "MISSING" if required else "absent"
                print(f"  {mark:<9}{label:<28}{pat}")
                if required:
                    missing.append((label, pat, claim))
                continue
            d = out / dest
            d.mkdir(parents=True, exist_ok=True)
            n = 0
            for f in files:
                try:
                    shutil.copy2(f, d / f.name)
                    n += 1
                except Exception as e:
                    print(f"           could not copy {f.name}: {e}")
            collected[label] = n
            print(f"  {'ok':<9}{label:<28}{n} file(s) -> {dest}/")

        # pipeline scripts, including the integrity checks
        sub("S1b  ANALYSIS SCRIPTS")
        sd = out / "scripts"
        sd.mkdir(parents=True, exist_ok=True)
        want = sorted(list(scripts.glob("0*.py")) + list(scripts.glob("annotate.py")) +
                      list(scripts.glob("offline_annotation.py")) +
                      list(scripts.glob("check_state.py")))
        for f in want:
            shutil.copy2(f, sd / f.name)
            print(f"  ok       {f.name}")
        if want:
            collected["analysis scripts"] = len(want)
        else:
            missing.append(("analysis scripts", "0*.py",
                            "the scripts that generate every table and figure"))
            print("  MISSING  no pipeline scripts found; pass --scripts <dir>")
        # the integrity checks live inside the annotation tools
        if any(f.name in ("annotate.py", "offline_annotation.py") for f in want):
            collected["integrity-check code"] = 1
            print("  ok       integrity-check code (inside the annotation tools)")
        else:
            missing.append(("integrity-check code", "annotate.py / offline_annotation.py",
                            "the annotation integrity checks are part of the tooling"))

        # ---- S2 environment ----------------------------------------------
        sub("S2  ENVIRONMENT LOCK")
        lock = out / "requirements-lock.txt"
        lines = [f"# generated {datetime.datetime.now().isoformat(timespec='seconds')}",
                 f"# python {sys.version.split()[0]} on {sys.platform}",
                 f"# executable {sys.executable}", ""]
        try:
            r = subprocess.run([sys.executable, "-m", "pip", "freeze"],
                               capture_output=True, text=True, timeout=180)
            body = r.stdout.strip()
            if body:
                lines.append(body)
        except Exception as e:
            lines.append(f"# pip freeze failed: {e}")
        lock.write_text("\n".join(lines) + "\n", encoding="utf-8")
        # v09.1.1 counted list ELEMENTS, and pip freeze output is appended as a
        # single multi-line element, so the count was always 1 and the
        # "npk == 0" guard could never fire. Count the written lines instead.
        written = lock.read_text(encoding="utf-8").splitlines()
        pkgs = [l for l in written if l.strip() and not l.startswith("#")]
        npk = len(pkgs)
        print(f"  written  requirements-lock.txt  ({npk} package(s))")
        need = ["numpy", "scipy", "matplotlib"]
        low = " ".join(pkgs).lower()
        absent = [n for n in need if n not in low]
        if absent:
            print(f"  ** the lock file does not name {absent}, which the manuscript")
            print(f"     states the evaluation harness requires. Either the freeze")
            print(f"     ran against a different interpreter or the claim is wrong.")
            missing.append(("environment lock", "pip freeze",
                            "exact versions are pinned in the released environment file"))
        else:
            print(f"  contains numpy, scipy and matplotlib as the manuscript states")
        print(f"  python   {sys.version.split()[0]}")
        collected["environment lock"] = 1
        if npk == 0:
            print("  ** pip freeze produced nothing; the lock file names no versions.")
            missing.append(("environment lock", "pip freeze",
                            "exact versions are pinned in the released environment file"))

        # v09.3.0 compared modification times here. That was the wrong
        # property: Expand-Archive and Copy-Item preserve the source timestamp,
        # so a figure copied from a release zip is always "older" than files
        # written afterwards, regardless of its content. The check produced a
        # false positive on a verified-correct figure. Report identity instead
        # and let the author compare against the manuscript.
        fdir = out / "figures"
        if fdir.exists():
            figs = sorted(fdir.glob("*.png"))
            if figs:
                print()
                print(f"  {len(figs)} figure file(s) collected. Verify that each figure")
                print("  in the manuscript matches the file of the same name here, by")
                print("  size or hash; timestamps are not evidence after a copy.")
                print()
                print(f"    {'file':<38}{'bytes':>10}  sha256 (first 16)")
                for f_ in figs:
                    print(f"    {f_.name:<38}{f_.stat().st_size:>10,}  "
                          f"{sha256(f_)[:16]}")
                extra = [f_.name for f_ in figs
                         if not f_.name.startswith(("fig1", "fig2", "fig3_", "fig4"))]
                if extra:
                    print()
                    print(f"  NOTE: {len(extra)} file(s) here are not among the four")
                    print("  figures in the manuscript:")
                    for e in extra:
                        print(f"    {e}")
                    print("  Keep them only if the README explains what they are;")
                    print("  an unexplained figure in a release invites the question")
                    print("  of which one the paper actually used.")

        # ---- S3 checksums -------------------------------------------------
        sub("S3  CHECKSUM MANIFEST")
        rows, total = [], 0
        for f in sorted(out.rglob("*")):
            if f.is_file() and f.name != "MANIFEST-RELEASE.txt":
                rows.append((str(f.relative_to(out)).replace("\\", "/"),
                             f.stat().st_size, sha256(f)))
                total += f.stat().st_size
        man = out / "MANIFEST-RELEASE.txt"
        with open(man, "w", encoding="utf-8") as fh:
            fh.write(f"# PLEF V2 release manifest\n")
            fh.write(f"# generated {datetime.datetime.now().isoformat(timespec='seconds')}\n")
            fh.write(f"# {len(rows)} files, {total:,} bytes\n")
            fh.write("# sha256  bytes  path\n")
            for p, sz, h in rows:
                fh.write(f"{h}  {sz}  {p}\n")
        agg = hashlib.sha256("".join(h for _, _, h in rows).encode()).hexdigest()
        print(f"  {len(rows)} files, {total:,} bytes ({total/1e6:.0f} MB)")
        print(f"  aggregate release hash: {agg}")
        big = [(p_, sz) for p_, sz, _ in rows if sz > 50_000_000]
        if big:
            print("  ** files over 50 MB, which some hosts reject:")
            for p_, sz in big:
                print(f"     {sz/1e6:>6.0f} MB  {p_}")
        if total > 100_000_000:
            print(f"  ** the release is {total/1e6:.0f} MB. GitHub warns above 1 GB and")
            print("     rejects single files above 100 MB. If this is too large,")
            print("     deposit the scored outputs in a data repository (Zenodo,")
            print("     OSF, Figshare) and cite the DOI, keeping code on GitHub.")

        # ---- S4 provenance verification -----------------------------------
        sub("S4  PROVENANCE VERIFICATION")
        known = {a[0] for a in ARTIFACTS} | {"analysis scripts", "integrity-check code",
                                             "environment lock"}
        bogus = sorted({n for _, needs in CLAIMS for n in needs} - known)
        if bogus:
            print(f"  INTERNAL ERROR: claims reference unknown artifact labels {bogus};")
            print("  the verification below would be vacuous. Fix the CLAIMS table.")
            return 3
        print()
        print("  Every claim the manuscript makes about a released artifact.")
        print()
        unmet = []
        for claim, needs in CLAIMS:
            have = [n for n in needs if collected.get(n)]
            ok = len(have) == len(needs)
            if not ok:
                unmet.append((claim, [n for n in needs if not collected.get(n)]))
            print(f"  {'OK ' if ok else 'X  '} {claim}")
            if not ok:
                print(f"        missing: {[n for n in needs if not collected.get(n)]}")

        # ---- S5 readme -----------------------------------------------------
        sub("S5  REPOSITORY README")
        rm = out / "README.md"
        rm.write_text(f"""# PLEF V2 -- analysis release

Generated {datetime.datetime.now().isoformat(timespec='seconds')} by
`scripts/09_release_assembly.py` v{SCRIPT_VERSION}.

This release exists so that every provenance claim in the manuscript can be
checked rather than taken on trust.

## Contents

| path | what it is |
|---|---|
| `DECISIONS.md` | analysis choices, each timestamped before the corresponding output |
| `AUDIT_RECONCILIATION.md` | reconciliation of item counts, throughput, chance benchmarks |
| `MANIFEST-RELEASE.txt` | SHA-256 and size for every file in this release |
| `manifest/` | input manifests with source-file checksums |
| `src/` | the framework core, its lexicons, the baseline adapter, the purity test |
| `scripts/` | every pipeline stage, and the annotation tools with their integrity checks |
| `scored/` | one row per document per corpus: the raw outputs behind every table |
| `tables/` | every table in the manuscript, machine-readable |
| `figures/` | the figures |
| `annotation/` | responses for all annotation rounds, including the rejected ones |
| `logs/` | the console log for every pipeline stage |
| `requirements-lock.txt` | the environment that produced these results |

## Reproducing

The framework core (`src/plef_core.py`) imports only the Python standard
library; `src/plef_purity.py` verifies this by importing it in a fresh process
with third-party packages blocked. The evaluation harness does require third
party packages, listed in `requirements-lock.txt`.

The NRC lexicons are distributed by their author under a research licence and
are not redistributed here. The relationship corpus consists of public Reddit
posts; the collection scripts are included and the post text is not
redistributed.

## Verifying this release

    python -c "import hashlib,sys;print(hashlib.sha256(open(sys.argv[1],'rb').read()).hexdigest())" <file>

and compare against `MANIFEST-RELEASE.txt`.

Aggregate release hash: `{agg}`
""", encoding="utf-8")
        print(f"  written  README.md")
        lic = out / "LICENSE.txt"
        if not lic.exists():
            lic.write_text("Add a licence before publishing. Code and data may "
                           "require different terms; the NRC lexicons are not "
                           "redistributable.\n", encoding="utf-8")
            print("  written  LICENSE.txt  (placeholder -- replace before publishing)")

        head("DONE")
        print(f"  release : {out}")
        print(f"  files   : {len(rows)}")
        print(f"  log     : {root / 'results' / 'forensics' / 'console_log_09.txt'}")
        print()
        if missing:
            print(f"  {len(missing)} REQUIRED ARTIFACT(S) MISSING:")
            for label, pat, claim in missing:
                print(f"    - {label}  ({pat})")
                print(f"      supports: \"{claim}\"")
        if unmet:
            print()
            print(f"  {len(unmet)} MANUSCRIPT CLAIM(S) NOT BACKED BY AN ARTIFACT:")
            for claim, need in unmet:
                print(f"    - \"{claim}\"  needs {need}")
            print()
            print("  Either produce the artifact or remove the claim from the")
            print("  manuscript. Do not submit while a claim is unbacked.")
            return 3
        print("  Every provenance claim in the manuscript is backed by a file in")
        print("  this release, and every file is checksummed. Publish this")
        print("  directory and cite it in the data availability statement.")
        return 0
    except Exception:
        print("\nUNHANDLED EXCEPTION"); traceback.print_exc(); return 3
    finally:
        sys.stdout = tee.stdout; tee.close()


if __name__ == "__main__":
    sys.exit(main())
