# -*- coding: utf-8 -*-
"""
PLEF V2 core -- twelve psycholinguistic metrics.
AUTOGENERATED by scripts/04_core_rebuild.py. Do not edit by hand.

STANDARD LIBRARY ONLY. This is verified by scripts/04 with an import blocker
that runs in a fresh subprocess; the build fails if anything outside the
standard library is reachable.

Lexicons are loaded from plef_lexicons.json, which was lifted verbatim from the
V1 implementation by AST. Nothing was retyped.

EVERY METRIC BELOW STATES ITS EXACT ALGORITHM. Where V2 differs from V1, the
difference and its reason are stated in the docstring, and the V1 form is kept
alongside so the change can be quantified rather than asserted.
"""
import collections
import itertools
import json
import math
import os
import re
import statistics

_HERE = os.path.dirname(os.path.abspath(__file__))
with open(os.path.join(_HERE, "plef_lexicons.json"), encoding="utf-8") as _f:
    _L = json.load(_f)

LEXICON = _L["LEXICON"]
NEGATORS = set(_L["NEGATORS"])
INTENSIFIERS = _L["INTENSIFIERS"]
DIMINISHERS = _L["DIMINISHERS"]
SARCASM_PATTERNS = _L["SARCASM_PATTERNS"]
ATTACHMENT = _L["ATTACHMENT"]
CONTROL_VERBS = _L["CONTROL_VERBS"]
APOLOGY_WORDS = _L["APOLOGY_WORDS"]
COGNITIVE_DISTORTIONS = _L["COGNITIVE_DISTORTIONS"]
HORSEMAN_PATTERNS = _L["HORSEMAN_PATTERNS"]
ARCHETYPES = _L["ARCHETYPES"]
ABSOLUTE_PAIRS = _L["ABSOLUTE_PAIRS"]
DISCLOSURE_TIERS = _L["DISCLOSURE_TIERS"]
STOP_WORDS = set(_L["STOP_WORDS"])

_TOK = re.compile(r"[a-z']+")
_SENT = re.compile(r"(?<=[.!?])\s+")
_WS = re.compile(r"\s+")

I_WORDS = {"i", "me", "my", "myself", "mine"}
YOU_WORDS = {"you", "your", "yourself", "yours"}
WE_WORDS = {"we", "us", "our", "ourselves", "ours"}

MIN_SENTS_TRAJECTORY = 4        # LEWI / NAVA are undefined below this
GASE_WEIGHTS = {"S": 0.30, "H": 0.25, "A": 0.25, "G": 0.20}
NSPL_WEIGHTS = {"G": 0.35, "SEM": 0.30, "TEG": 0.20, "PTI": 0.15}


def tokenize(text):
    return _TOK.findall(text.lower())


def sentences(text):
    return [s.strip() for s in _SENT.split(text) if s.strip()]


# ---------------------------------------------------------------------------
# SENTIMENT CORE
# ---------------------------------------------------------------------------
def score_sentence(sent_text):
    """Compound sentiment for one sentence.

    Algorithm, stated exactly:
      1. tokenise on [a-z']+
      2. a negator marks the following 4 tokens as negated (multiplier -0.7)
      3. the 2 tokens preceding a scored token supply an intensity multiplier
      4. weighted sum of  entry.s * entry.i * modifier
      5. multi-word lexicon phrases matched against the lowercased sentence
      6. if any sarcasm pattern matches, positive contributions are negated
      7. compound = sum / sqrt(sum^2 + 15)      [Hutto & Gilbert 2014 form]

    Returns (compound, emotion_counts, sarcasm_flag, horseman_hits).
    """
    tokens = tokenize(sent_text)
    text_l = sent_text.lower()
    negated = set()
    for i, tok in enumerate(tokens):
        if tok in NEGATORS:
            for j in range(i + 1, min(i + 5, len(tokens))):
                negated.add(j)
    scores = []
    emo = collections.defaultdict(int)
    horse = []
    for i, tok in enumerate(tokens):
        mod_tok = " ".join(tokens[max(0, i - 2):i])
        modifier = 1.0
        for w, m in INTENSIFIERS.items():
            if w in mod_tok:
                modifier = max(modifier, m)
        for w, m in DIMINISHERS.items():
            if w in mod_tok:
                modifier = min(modifier, m)
        e = LEXICON.get(tok)
        if e:
            s = e["s"] * e.get("i", 1.0) * modifier
            if i in negated:
                s *= -0.7
            scores.append(s)
            for x in e.get("e", []):
                emo[x] += 1
            if "horseman" in e:
                horse.append(e["horseman"])
    for phrase, e in LEXICON.items():
        if " " in phrase and phrase in text_l:
            scores.append(e["s"] * e.get("i", 1.0))
            for x in e.get("e", []):
                emo[x] += 1
            if "horseman" in e:
                horse.append(e["horseman"])
    sarcasm = any(re.search(p, text_l) for p in SARCASM_PATTERNS)
    if sarcasm:
        scores = [-s if s > 0 else s for s in scores]
    tot = sum(scores)
    comp = tot / math.sqrt(tot * tot + 15) if scores else 0.0
    return round(comp, 6), dict(emo), sarcasm, horse


def sentence_scores(text):
    return [score_sentence(s)[0] for s in sentences(text)]


# ---------------------------------------------------------------------------
# 1. LEWI
# ---------------------------------------------------------------------------
def compute_lewi(scores):
    """Linguistic Emotional Watershed Index.

    V2 PRIMARY -- the PUBLISHED definition, implemented exactly:

        w   = max(1, floor(N/4))                     smoothing half-window
        S~  = centred moving average of S over w
        i*  = argmax over 1<=i<=N-2 of |S~[i+1] - 2*S~[i] + S~[i-1]|
        dLEWI = mean(S[0:i*]) - mean(S[i*:N])        DISJOINT segments

    The published formula writes the two segments as S(1:i*) and S(i*:N),
    which places i* in both. The implementation uses a disjoint split at i*;
    that is what is documented here.

    V1's code did something else entirely: it looked for sign changes in the
    FIRST derivative, fell back to the maximum absolute slope, and defaulted to
    the midpoint when neither fired (Reviewer 2, point 3). compute_lewi_v1
    reproduces it so the disagreement can be measured.

    Returns (index, pre_mean, post_mean, drop, smoothed) or (None, ...) when
    N < 4, in which case the metric is undefined and must be excluded rather
    than treated as zero.
    """
    n = len(scores)
    if n < MIN_SENTS_TRAJECTORY:
        return None, None, None, None, list(scores)
    w = max(1, n // 4)
    sm = _smooth(scores, w)
    best_i, best_v = None, -1.0
    for i in range(1, len(sm) - 1):
        v = abs(sm[i + 1] - 2.0 * sm[i] + sm[i - 1])
        if v > best_v + 1e-12:
            best_v, best_i = v, i
    if best_i is None:
        best_i = n // 2
    pre = sum(scores[:best_i]) / best_i
    post = sum(scores[best_i:]) / (n - best_i)
    return best_i, round(pre, 6), round(post, 6), round(pre - post, 6), sm


def compute_lewi_v1(scores):
    """V1's algorithm, reproduced verbatim for the disagreement measurement."""
    n = len(scores)
    if n < 4:
        return None, 0.0
    w = max(1, n // 4)
    sm = _smooth(scores, w)
    if max(sm) - min(sm) < 0.01:
        sm = list(scores)
    d = [sm[i + 1] - sm[i] for i in range(len(sm) - 1)]
    best_idx, best_mag = n // 2, 0.0
    for i in range(1, len(d) - 1):
        if d[i - 1] * d[i] < 0:
            mag = abs(d[i - 1] - d[i])
            if mag > best_mag:
                best_mag, best_idx = mag, i
    if best_mag == 0.0 and d:
        best_idx = max(range(len(d)), key=lambda i: abs(d[i]))
    pre = sum(scores[:best_idx]) / max(1, best_idx)
    post = sum(scores[best_idx:]) / max(1, n - best_idx)
    return best_idx, round(pre - post, 6)


def _smooth(sig, w):
    out = []
    for i in range(len(sig)):
        lo, hi = max(0, i - w), min(len(sig), i + w + 1)
        out.append(sum(sig[lo:hi]) / (hi - lo))
    return out


# ---------------------------------------------------------------------------
# 2. TEG
# ---------------------------------------------------------------------------
def compute_teg(scores):
    """Temporal Emotional Gradient = mean absolute successive difference.

        TEG = (1/(N-1)) * sum_{i=2..N} |s_i - s_{i-1}|

    The manuscript printed 1/N over N-1 differences (Reviewer 2, point 4).
    V2 uses 1/(N-1), which is what the code always computed and what the
    statistic actually is.

    This is MASD, a standard affect-dynamics measure (Kuppens et al. 2010;
    Houben et al. 2015) applied to sentence-level narrative sentiment. It is
    not a novel metric and V2 does not describe it as one.
    """
    if len(scores) < 2:
        return None
    d = [abs(scores[i] - scores[i - 1]) for i in range(1, len(scores))]
    return round(sum(d) / len(d), 6)


# ---------------------------------------------------------------------------
# 3. NAVA
# ---------------------------------------------------------------------------
NAVA_CLASSES = ("tragic", "mildly_declining", "flat", "mildly_improving",
                "redemptive")


def compute_nava(scores):
    """Narrative Arc Valence Asymmetry.

        k    = max(1, floor(N/4)) if N < 9 else max(1, floor(N/3))
        NAVA = mean(S[0:k]) - mean(S[N-k:N])

    SIGN CONVENTION, fixed. POSITIVE NAVA means the narrative ENDS WORSE than
    it starts, i.e. the tragic direction. The manuscript's section 3.2.3 said
    this and section 6.1 contradicted it (Reviewer 2, point 5).

    FIVE classes are published, not three. The implementation always had five;
    the manuscript reported three and left 0.05 < |NAVA| < 0.15 undefined.

        NAVA >  0.15   tragic
        NAVA >  0.05   mildly_declining
       |NAVA| <= 0.05  flat
        NAVA < -0.15   redemptive
        else           mildly_improving

    Undefined below 4 sentences; returns None so callers must exclude rather
    than treat as zero.
    """
    n = len(scores)
    if n < MIN_SENTS_TRAJECTORY:
        return None, None
    k = max(1, n // 4 if n < 9 else n // 3)
    nava = sum(scores[:k]) / k - sum(scores[n - k:]) / k
    nava = round(nava, 6)
    if nava > 0.15:
        arc = "tragic"
    elif nava > 0.05:
        arc = "mildly_declining"
    elif nava >= -0.05:
        arc = "flat"
    elif nava >= -0.15:
        arc = "mildly_improving"
    else:
        arc = "redemptive"
    return nava, arc


# ---------------------------------------------------------------------------
# 4. PTI
# ---------------------------------------------------------------------------
def compute_pti(text, smoothed=True):
    """Pronoun Triangulation Index.

        smoothed   (I - You) / (I + You + We + 1)      [V1 form]
        unsmoothed (I - You) / (I + You + We)          [None when denominator 0]

    The +1 is an undocumented smoothing term that shrinks PTI toward zero as a
    function of pronoun count, making it length-dependent. Both forms are
    exposed so the confound is measured rather than argued about.
    """
    t = tokenize(text)
    I = sum(1 for x in t if x in I_WORDS)
    Y = sum(1 for x in t if x in YOU_WORDS)
    W = sum(1 for x in t if x in WE_WORDS)
    den = I + Y + W
    if smoothed:
        return round((I - Y) / (den + 1), 6), {"I": I, "You": Y, "We": W}
    if den == 0:
        return None, {"I": I, "You": Y, "We": W}
    return round((I - Y) / den, 6), {"I": I, "You": Y, "We": W}


# ---------------------------------------------------------------------------
# 5. PAI
# ---------------------------------------------------------------------------
def compute_pai(text):
    """Power Asymmetry Index.

    V2 PRIMARY -- the pronoun term is REMOVED:

        C_dom = min(1, control_verb_hits / (0.1*n_words + 1))
        A_dom = 0 if no apology words else min(1, 0.5 + apology_hits/10)
        PAI   = (C_dom + A_dom) / 2

    V1's PAI averaged in I_dom = |I-You|/(I+You), built from the same pronoun
    counts as PTI, so PTI x PAI was partly an algebraic identity (Reviewer 2,
    point 7). A null with random counts and no text reaches r = 0.554 in the
    regime every corpus occupies. Dropping the term makes PAI independent of
    PTI by construction; pai_v1 is retained so the coupling is reportable.
    """
    t = tokenize(text)
    n = max(1, len(t))
    c_hits = sum(t.count(v) for v in CONTROL_VERBS)
    c_dom = min(1.0, c_hits / (n * 0.1 + 1))
    low = text.lower()
    apo = sum(low.count(w) for w in APOLOGY_WORDS)
    a_dom = 0.0 if apo == 0 else min(1.0, 0.5 + apo / 10.0)
    pai = (c_dom + a_dom) / 2.0
    I = sum(1 for x in t if x in {"i", "me", "my"})
    Y = sum(1 for x in t if x in {"you", "your", "yourself"})
    i_dom = abs(I - Y) / max(1, I + Y)
    pai_v1 = min(1.0, (c_dom + i_dom + a_dom) / 3.0)
    return (round(min(1.0, pai), 6),
            {"C_dom": round(c_dom, 6), "A_dom": round(a_dom, 6),
             "I_dom_excluded": round(i_dom, 6), "pai_v1": round(pai_v1, 6)})


# ---------------------------------------------------------------------------
# 6. RCI
# ---------------------------------------------------------------------------
def compute_rci(text):
    """Relational Coherence Index: mean pairwise Jaccard over content words.

    Segments are paragraphs when at least 2 exist, otherwise sentences.
    Returns None when fewer than 2 segments exist, so an undefined value is
    never recorded as 0.0 (V1 returned 0.0 and polluted every correlation).
    """
    segs = [p.strip() for p in re.split(r"\n\s*\n", text) if p.strip()]
    if len(segs) < 2:
        segs = [s for s in sentences(text) if len(s) > 15]
    if len(segs) < 2:
        return None
    sets = [set(w for w in tokenize(s)
                if w not in STOP_WORDS and len(w) >= 3 and w.isalpha())
            for s in segs]
    js = []
    for a, b in itertools.combinations(sets, 2):
        u = len(a | b)
        js.append(len(a & b) / u if u else 0.0)
    return round(sum(js) / len(js), 6) if js else None


# ---------------------------------------------------------------------------
# 7. GASE  (+ genuine renormalised ablation)
# ---------------------------------------------------------------------------
def gase_components(text, scores, emo_totals, horsemen_total, n_sents):
    """The four GASE components, each actually computed."""
    S = statistics.mean(scores) if scores else 0.0
    vals = [v for v in emo_totals.values() if v > 0]
    tot = sum(vals)
    if tot > 0 and len(vals) > 1:
        ps = [v / tot for v in vals]
        H = -sum(p * math.log(p, 2) for p in ps)
        H_norm = H / math.log(max(2, len(vals)), 2)
    else:
        H_norm = 0.0
    t = tokenize(text)
    joined = " ".join(t)
    anx = sum(joined.count(w) for w in ATTACHMENT.get("anxious", []))
    avo = sum(joined.count(w) for w in ATTACHMENT.get("avoidant", []))
    sec = sum(joined.count(w) for w in ATTACHMENT.get("secure", []))
    A = min(1.0, (anx * 1.2 + avo * 0.8) / (10 + sec + 1))
    G = min(1.0, horsemen_total / (max(1, n_sents) * 0.5 + 1))
    return {"S": S, "H": H_norm, "A": A, "G": G}


def compute_gase(comp):
    """GASE = 0.30*S + 0.25*(1-H) + 0.25*(1-A) + 0.20*(1-G), clipped to [-1,1]."""
    w = GASE_WEIGHTS
    g = (w["S"] * comp["S"] + w["H"] * (1 - comp["H"]) +
         w["A"] * (1 - comp["A"]) + w["G"] * (1 - comp["G"]))
    return round(max(-1.0, min(1.0, g)), 6)


def gase_ablation(comp):
    """Genuine leave-one-out ablation with RENORMALISED remaining weights.

    V1's published ablation subtracted weight x 0.5, a hardcoded constant; the
    component values were never read, which is why removing Entropy and removing
    Attachment gave identical results to four decimals. That table measured
    nothing.

    Renormalisation matters: without it, dropping a component lowers the score
    by its weight by definition, which proves nothing about the component.
    """
    w = GASE_WEIGHTS
    vals = {"S": comp["S"], "H": 1 - comp["H"], "A": 1 - comp["A"],
            "G": 1 - comp["G"]}
    full = compute_gase(comp)
    out = {"full": full}
    for drop in ("S", "H", "A", "G"):
        keep = {k: v for k, v in w.items() if k != drop}
        tot = sum(keep.values())
        g = sum((wt / tot) * vals[k] for k, wt in keep.items())
        g = max(-1.0, min(1.0, g))
        out[f"without_{drop}"] = round(g, 6)
        out[f"delta_{drop}"] = round(g - full, 6)
    return out


# ---------------------------------------------------------------------------
# 8. CD-index
# ---------------------------------------------------------------------------
def compute_cd_index(text):
    """Cognitive distortion index: mean of 12 capped per-distortion densities."""
    n_words = len(tokenize(text))
    cap = max(1.0, n_words / 200.0)
    per = {}
    for name, info in COGNITIVE_DISTORTIONS.items():
        hits = 0
        for pat in info["patterns"]:
            hits += len(re.findall(pat, text, re.IGNORECASE))
        per[name] = min(1.0, hits / cap)
    return round(sum(per.values()) / len(per), 6), per


# ---------------------------------------------------------------------------
# 9. VADS
# ---------------------------------------------------------------------------
def compute_vads(text):
    """Vulnerability-Authenticity Disclosure Score, weighted tier density."""
    n = max(1, len(tokenize(text)))
    tot, tiers = 0.0, {}
    for tier, info in DISCLOSURE_TIERS.items():
        hits = sum(len(re.findall(p, text, re.IGNORECASE))
                   for p in info["patterns"])
        tiers[tier] = hits
        tot += info["weight"] * hits
    return round(min(1.0, (tot / n) * 10), 6), tiers


# ---------------------------------------------------------------------------
# 10. TIES
# ---------------------------------------------------------------------------
def compute_ties(text, emo_totals):
    """Inconsistency entropy x absolute-term contradiction density.

    EXPLICITLY NOT a gaslighting detector. It is an inconsistency measure and
    the manuscript must say so wherever it appears.
    """
    segs = [p.strip() for p in re.split(r"\n\s*\n", text) if p.strip()]
    if len(segs) < 2:
        segs = sentences(text)
    if len(segs) < 2:
        return None
    contra = 0
    for s in segs:
        low = s.lower()
        for a, b in ABSOLUTE_PAIRS:
            if re.search(a, low) and re.search(b, low):
                contra += 1
    vals = [v for v in emo_totals.values() if v > 0]
    tot = sum(vals)
    if tot > 0 and len(vals) > 1:
        ps = [v / tot for v in vals]
        H = -sum(p * math.log(p, 2) for p in ps) / math.log(max(2, len(vals)), 2)
    else:
        H = 0.0
    return round(H * (contra / len(segs)), 6)


# ---------------------------------------------------------------------------
# 11. NSPL  (LSA fusion, deterministic)
# ---------------------------------------------------------------------------
def semantic_coherence(text, max_sents=60, dims=3, iters=60):
    """Mean off-diagonal cosine similarity of LSA sentence vectors.

    TF-IDF then a truncated SVD by DETERMINISTIC power iteration with a fixed
    non-random initial vector. V1 used NumPy SVD when available and stochastic
    power iteration otherwise, so results depended on the environment and the
    manuscript never stated which path produced them (Reviewer 2, point 8).
    There is one path here and it is deterministic.

    Returns None for fewer than 2 sentences.
    """
    sents = sentences(text)[:max_sents]
    if len(sents) < 2:
        return None
    docs = [[w for w in tokenize(s) if w not in STOP_WORDS and len(w) >= 3]
            for s in sents]
    vocab = sorted({w for d in docs for w in d})
    if not vocab:
        return None
    idx = {w: i for i, w in enumerate(vocab)}
    N = len(docs)
    df = collections.Counter(w for d in docs for w in set(d))
    M = []
    for d in docs:
        tf = collections.Counter(d)
        ln = max(1, len(d))
        row = [0.0] * len(vocab)
        for w, c in tf.items():
            row[idx[w]] = (c / ln) * math.log((1 + N) / (1 + df[w]) + 1.0)
        M.append(row)
    comps = []
    R = [r[:] for r in M]
    for k in range(min(dims, len(vocab), N)):
        v = [1.0 / math.sqrt(len(vocab))] * len(vocab)   # fixed, deterministic
        for _ in range(iters):
            u = [sum(R[i][j] * v[j] for j in range(len(vocab))) for i in range(N)]
            nu = math.sqrt(sum(x * x for x in u))
            if nu < 1e-12:
                break
            u = [x / nu for x in u]
            nv = [sum(R[i][j] * u[i] for i in range(N)) for j in range(len(vocab))]
            nn = math.sqrt(sum(x * x for x in nv))
            if nn < 1e-12:
                break
            v = [x / nn for x in nv]
        comps.append([sum(R[i][j] * v[j] for j in range(len(vocab)))
                      for i in range(N)])
        for i in range(N):
            proj = comps[-1][i]
            for j in range(len(vocab)):
                R[i][j] -= proj * v[j]
    if not comps:
        return None
    vecs = [[comps[k][i] for k in range(len(comps))] for i in range(N)]
    sims = []
    for a, b in itertools.combinations(range(N), 2):
        na = math.sqrt(sum(x * x for x in vecs[a]))
        nb = math.sqrt(sum(x * x for x in vecs[b]))
        if na < 1e-12 or nb < 1e-12:
            continue
        sims.append(sum(vecs[a][k] * vecs[b][k] for k in range(len(comps)))
                    / (na * nb))
    return round(sum(sims) / len(sims), 6) if sims else None


def compute_nspl(gase, sem_coh, teg, pti):
    """NSPL = 0.35*Ghat + 0.30*SemCoh + 0.20*(1-TEGn) + 0.15*(1-|PTI|).

    Ghat = (GASE+1)/2, TEGn = min(1, TEG). Returns None if any input is None,
    rather than substituting a zero.

    NOTE for the manuscript: this layer is Latent Semantic Analysis, a linear
    matrix factorisation. It is NOT neural, and PLEF must not be described as
    neuro-symbolic on the strength of it (Reviewer 2, point 1).
    """
    if gase is None or sem_coh is None or teg is None or pti is None:
        return None
    w = NSPL_WEIGHTS
    v = (w["G"] * ((gase + 1) / 2) + w["SEM"] * sem_coh +
         w["TEG"] * (1 - min(1.0, teg)) + w["PTI"] * (1 - abs(pti)))
    return round(max(0.0, min(1.0, v)), 6)


# ---------------------------------------------------------------------------
# 12. RASP
# ---------------------------------------------------------------------------
def compute_rasp(text):
    """Archetype template match over six narrative archetypes. EXPLORATORY."""
    low = text.lower()
    out = {}
    for name, info in ARCHETYPES.items():
        hits = sum(1 for s in info["signals"] if s in low)
        out[name] = round(min(1.0, hits / max(1, len(info["signals"]) * 0.4)), 6)
    dom = max(out, key=lambda k: out[k])
    return out, (dom if out[dom] > 0 else None)


# ---------------------------------------------------------------------------
def analyse(text):
    """Every metric for one text. Undefined metrics are None, never 0.0."""
    sents = sentences(text)
    n_sents = len(sents)
    res = [score_sentence(s) for s in sents]
    scores = [r[0] for r in res]
    emo = collections.Counter()
    horse = 0
    for _, e, _, h in res:
        for k, v in e.items():
            emo[k] += v
        horse += len(h)
    lewi_i, pre, post, drop, _ = compute_lewi(scores)
    lewi_v1_i, lewi_v1_drop = compute_lewi_v1(scores) if n_sents >= 4 else (None, None)
    nava, arc = compute_nava(scores)
    teg = compute_teg(scores)
    pti, pron = compute_pti(text, smoothed=True)
    pti_u, _ = compute_pti(text, smoothed=False)
    pai, pai_parts = compute_pai(text)
    comp = gase_components(text, scores, emo, horse, n_sents)
    gase = compute_gase(comp)
    cd, _ = compute_cd_index(text)
    vads, _ = compute_vads(text)
    ties = compute_ties(text, emo)
    rci = compute_rci(text)
    sem = semantic_coherence(text)
    nspl = compute_nspl(gase, sem, teg, pti)
    rasp, dom = compute_rasp(text)
    return {
        "n_sents": n_sents, "n_words": len(tokenize(text)),
        "sentiment_mean": round(statistics.mean(scores), 6) if scores else None,
        "lewi_idx": lewi_i, "lewi_pre": pre, "lewi_post": post, "lewi_drop": drop,
        "lewi_v1_idx": lewi_v1_i, "lewi_v1_drop": lewi_v1_drop,
        "teg": teg, "nava": nava, "nava_arc": arc,
        "gase": gase, "gase_S": round(comp["S"], 6), "gase_H": round(comp["H"], 6),
        "gase_A": round(comp["A"], 6), "gase_G": round(comp["G"], 6),
        "pti": pti, "pti_unsmoothed": pti_u,
        "pai": pai, "pai_v1": pai_parts["pai_v1"],
        "pai_C_dom": pai_parts["C_dom"], "pai_A_dom": pai_parts["A_dom"],
        "rci": rci, "cd_index": cd, "vads": vads, "ties": ties,
        "sem_coherence": sem, "nspl": nspl, "rasp_dominant": dom,
        "horsemen_total": horse,
    }
