# -*- coding: utf-8 -*-
"""
PLEF V2 -- unified baseline adapter.
AUTOGENERATED by scripts/02_baseline_environment.py. Do not edit by hand.

Every baseline exposes score(text) -> float in [-1, 1].
Scores are comparable in SIGN and ORDER, never in absolute scale.

DECLARED ARBITRARY CHOICES (provenance in DECISIONS.md):
  D1 Empath polarity uses a broad affect-category set; narrow variant retained.
  D2 AFINN normalisation: four variants, primary is 'sqrt'.
  D3 labMT stop band [4.0, 6.0], centre 5.0, scale 4.0. labMT measures
     HAPPINESS, not polarity: its zero point is NOT neutral.
  D4 Threshold +/-0.05 uniformly. AUC (threshold-free) is the primary metric.
"""
import math
import os
import re

_TOK_APOS = re.compile(r"[a-z']+")
_TOK_ALPHA = re.compile(r"[a-z]+")


def _tokens(text):
    return _TOK_APOS.findall(text.lower())


class _Base:
    name = "base"
    size = 0
    def score(self, text):
        raise NotImplementedError
    def coverage(self, text):
        return -1.0


class VaderBaseline(_Base):
    name = "vader"
    def __init__(self):
        from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
        self._a = SentimentIntensityAnalyzer()
        self.size = len(self._a.lexicon)
    def score(self, text):
        if not text or not text.strip():
            return 0.0
        return float(self._a.polarity_scores(text)["compound"])
    def coverage(self, text):
        t = _tokens(text)
        if not t:
            return 0.0
        return sum(1 for w in t if w in self._a.lexicon) / len(t)


class NRCBaseline(_Base):
    """Real NRC EmoLex v0.92."""
    name = "nrc"
    def __init__(self, path):
        pos, neg, emo = set(), set(), {}
        with open(path, encoding="utf-8", errors="replace") as f:
            for line in f:
                p = line.rstrip("\n").rstrip("\r").split("\t")
                if len(p) != 3:
                    continue
                w, cat, val = p[0].strip(), p[1].strip().lower(), p[2].strip()
                if val != "1":
                    continue
                if cat == "positive":
                    pos.add(w)
                elif cat == "negative":
                    neg.add(w)
                else:
                    emo.setdefault(cat, set()).add(w)
        self.pos, self.neg, self.emo = pos, neg, emo
        allw = set(pos) | set(neg)
        for s in emo.values():
            allw |= s
        self.vocab = allw
        # size_vocab  : every term in the file (compare against 14,182)
        # size_nonzero: terms with >=1 non-zero association (about 6,468)
        # Script 02 compared the second against the first and warned about a
        # correct file. Both are exposed so the right pair is compared.
        self.size_vocab = len(allw)
        self.size_nonzero = len(allw)
        self.size = len(allw)
    def score(self, text):
        t = _tokens(text)
        if not t:
            return 0.0
        p = sum(1 for w in t if w in self.pos)
        n = sum(1 for w in t if w in self.neg)
        return 0.0 if p + n == 0 else (p - n) / float(p + n)
    def coverage(self, text):
        t = _tokens(text)
        if not t:
            return 0.0
        return sum(1 for w in t if w in self.vocab) / len(t)
    def emotions(self, text):
        t = _tokens(text)
        d = max(1, len(t))
        return {c: sum(1 for w in t if w in s) / d for c, s in self.emo.items()}


class EmpathBaseline(_Base):
    """LIWC-analogue (Fast, Chen & Bernstein, CHI 2016; mean r=0.906 vs LIWC).

    D1 PROVENANCE, POST HOC: the narrow positive_emotion/negative_emotion pair
    was tried first and returned 0.000 on two of five hand-written known-answer
    sentences. The broad set below was then adopted. Categories were chosen by
    NAME only and never tuned against any evaluation corpus. Both variants are
    scored and reported.
    """
    name = "empath"
    POS_BROAD = ("positive_emotion", "joy", "love", "affection", "optimism",
                 "contentment", "cheerfulness", "trust", "celebration",
                 "achievement", "gain", "fun", "politeness", "sympathy",
                 "friends", "giving", "healing", "beauty", "pride")
    NEG_BROAD = ("negative_emotion", "sadness", "anger", "hate", "disgust",
                 "fear", "suffering", "pain", "shame", "nervousness",
                 "violence", "rage", "envy", "disappointment", "neglect",
                 "deception", "crime", "death", "injury", "weakness",
                 "aggression", "horror", "torment", "exasperation",
                 "irritability", "ridicule")
    POS_NARROW = ("positive_emotion",)
    NEG_NARROW = ("negative_emotion",)
    def __init__(self, mode="broad"):
        from empath import Empath
        self._e = Empath()
        cats = set(self._e.cats)
        p, n = (self.POS_BROAD, self.NEG_BROAD) if mode == "broad" \
            else (self.POS_NARROW, self.NEG_NARROW)
        self.mode = mode
        self.pos = tuple(c for c in p if c in cats)
        self.neg = tuple(c for c in n if c in cats)
        self.size = len(self._e.cats)
    def score(self, text):
        if not text or not text.strip():
            return 0.0
        r = self._e.analyze(text, normalize=True) or {}
        p = sum(float(r.get(c, 0.0)) for c in self.pos)
        n = sum(float(r.get(c, 0.0)) for c in self.neg)
        return 0.0 if p + n == 0 else (p - n) / (p + n)
    def categories(self, text):
        return self._e.analyze(text, normalize=True) or {}
    def coverage(self, text):
        """Fraction of tokens falling in ANY built-in Empath category."""
        t = _tokens(text)
        if not t:
            return 0.0
        r = self._e.analyze(text, normalize=False) or {}
        hits = sum(float(v) for v in r.values())
        return min(1.0, hits / len(t))


class AfinnBaseline(_Base):
    """AFINN-en-165 (Nielsen 2011).

    D2 ARBITRARY: AFINN returns an unbounded integer sum; a normalisation must
    be chosen and there is no published constant. Variants:
      sqrt  sum / (5*sqrt(n_tokens))   [declared primary]
      dens  sum / n_tokens
      mean  sum / (5*n_matched)
      tanh  tanh(sum/5)
    """
    name = "afinn"
    def __init__(self, mode="sqrt"):
        from afinn import Afinn
        self._a = Afinn()
        self.mode = mode
        self.size = 3382
    def _raw(self, text):
        try:
            return float(self._a.score(text))
        except Exception:
            return 0.0
    def _matched(self, text):
        try:
            return len(self._a.find_all(text))
        except Exception:
            return 0
    def score(self, text):
        t = _tokens(text)
        if not t:
            return 0.0
        s = self._raw(text)
        if self.mode == "dens":
            return max(-1.0, min(1.0, s / len(t)))
        if self.mode == "mean":
            m = self._matched(text) or 1
            return max(-1.0, min(1.0, s / (5.0 * m)))
        if self.mode == "tanh":
            return math.tanh(s / 5.0)
        return max(-1.0, min(1.0, s / (5.0 * (len(t) ** 0.5))))
    def coverage(self, text):
        t = _tokens(text)
        if not t:
            return 0.0
        return min(1.0, self._matched(text) / len(t))


class HuLiuBaseline(_Base):
    name = "huliu"
    def __init__(self):
        from nltk.corpus import opinion_lexicon
        self.pos = set(opinion_lexicon.positive())
        self.neg = set(opinion_lexicon.negative())
        self.size = len(self.pos) + len(self.neg)
    def score(self, text):
        t = _tokens(text)
        p = sum(1 for w in t if w in self.pos)
        n = sum(1 for w in t if w in self.neg)
        return 0.0 if p + n == 0 else (p - n) / float(p + n)
    def coverage(self, text):
        t = _tokens(text)
        if not t:
            return 0.0
        return sum(1 for w in t if w in self.pos or w in self.neg) / len(t)


class LabMTBaseline(_Base):
    """labMT happiness lexicon (Dodds & Danforth), as used by Reagan et al. 2016.

    labMTsimple's stopper() raises TypeError in the current release, so the
    standard procedure is implemented directly here.
    D3: labMT measures HAPPINESS, not polarity. Its zero point is not neutral
    and it is strongly positively shifted on ordinary text. This must be stated
    wherever labMT is reported.
    """
    name = "labmt"
    def __init__(self, lo=4.0, hi=6.0, center=5.0, scale=4.0):
        from labMTsimple.storyLab import emotionFileReader
        d, _v, _w = emotionFileReader(stopval=0.0, lang="english", returnVector=True)
        self.h = {}
        for w, row in d.items():
            try:
                self.h[w] = float(row[1])
            except (IndexError, ValueError, TypeError):
                continue
        self.lo, self.hi, self.center, self.scale = lo, hi, center, scale
        self.size = len(self.h)
    def score(self, text):
        vals = [self.h[w] for w in _tokens(text)
                if w in self.h and not (self.lo <= self.h[w] <= self.hi)]
        if not vals:
            return 0.0
        return max(-1.0, min(1.0, (sum(vals) / len(vals) - self.center) / self.scale))
    def coverage(self, text):
        t = _tokens(text)
        if not t:
            return 0.0
        return sum(1 for w in t if w in self.h) / len(t)


# --------------------------------------------------------------------------
# NRC companion lexicons -- VALIDATION INSTRUMENTS, NOT BASELINES.
# --------------------------------------------------------------------------
class VADLexicon:
    """NRC Valence-Arousal-Dominance. External criterion for PAI: dominance is
    annotated independently of any pronoun count, so it is not circular."""
    name = "nrc_vad"
    def __init__(self, path):
        self.v, self.a, self.d = {}, {}, {}
        with open(path, encoding="utf-8", errors="replace") as f:
            for line in f:
                p = line.rstrip("\n").rstrip("\r").split("\t")
                if len(p) < 4:
                    continue
                w = p[0].strip()
                try:
                    self.v[w] = float(p[1]); self.a[w] = float(p[2]); self.d[w] = float(p[3])
                except ValueError:
                    continue
        self.size = len(self.v)
    def _mean(self, table, text):
        vals = [table[w] for w in _tokens(text) if w in table]
        return sum(vals) / len(vals) if vals else None
    def valence(self, text): return self._mean(self.v, text)
    def arousal(self, text): return self._mean(self.a, text)
    def dominance(self, text): return self._mean(self.d, text)


class EmoIntLexicon:
    """NRC Emotion Intensity. External criterion for TEG: the intensity
    sequence is not derived from PLEF's own compound score."""
    name = "nrc_emoint"
    def __init__(self, path):
        self.t = {}
        with open(path, encoding="utf-8", errors="replace") as f:
            for line in f:
                p = line.rstrip("\n").rstrip("\r").split("\t")
                if len(p) < 3:
                    continue
                try:
                    s = float(p[2])
                except ValueError:
                    continue
                self.t.setdefault(p[0].strip(), {})[p[1].strip().lower()] = s
        self.size = len(self.t)
    def intensity(self, text):
        vals = []
        for w in _tokens(text):
            d = self.t.get(w)
            if d:
                vals.append(max(d.values()))
        return sum(vals) / len(vals) if vals else 0.0


# --------------------------------------------------------------------------
# LEGACY V1 TOYS -- supplementary error quantification ONLY.
# These must NEVER appear under the names VADER, NRC or LIWC.
# --------------------------------------------------------------------------
class LegacyToy(_Base):
    def __init__(self, name, kind, table):
        self.name, self.kind, self.table = name, kind, table
        self.size = len(table)
    def _toks(self, text):
        low = text.lower()
        return _TOK_ALPHA.findall(low) if self.kind == "nrc" else _TOK_APOS.findall(low)
    def score(self, text):
        toks = self._toks(text)
        if self.kind == "vader":
            total = 0.0
            for i, tok in enumerate(toks):
                if tok in self.table:
                    val = self.table[tok]
                    if any(n in toks[max(0, i - 3):i]
                           for n in ("not", "never", "no", "neither", "nor", "nothing")):
                        val *= -0.74
                    total += val
            return round(total / ((total ** 2 + 15) ** 0.5), 4)
        if self.kind == "nrc":
            c = {}
            for tok in toks:
                if tok in self.table:
                    for e, v in self.table[tok].items():
                        c[e] = c.get(e, 0) + v
            tot = max(1, len(toks))
            return round(c.get("positive", 0) / tot - c.get("negative", 0) / tot, 4)
        if self.kind == "liwc":
            n = max(1, len(toks))
            cnt = {cat: sum(1 for t in toks if t in seeds) * 100.0 / n
                   for cat, seeds in self.table.items()}
            p = cnt.get("Positive Emotion", 0.0)
            g = cnt.get("Negative Emotion", 0.0)
            return round((p - g) / max(1, p + g + 0.001), 4) if p + g > 0 else 0.0
        return 0.0
    def coverage(self, text):
        toks = self._toks(text)
        if not toks:
            return 0.0
        if self.kind == "liwc":
            vocab = set()
            for s in self.table.values():
                vocab |= set(s)
        else:
            vocab = set(self.table)
        return sum(1 for w in toks if w in vocab) / len(toks)


def load_all(nrc_path, legacy_path=None, include_legacy=True,
             empath_mode="broad", afinn_mode="sqrt"):
    out = {}
    out["vader"] = VaderBaseline()
    out["nrc"] = NRCBaseline(nrc_path)
    out["empath"] = EmpathBaseline(empath_mode)
    out["afinn"] = AfinnBaseline(afinn_mode)
    out["huliu"] = HuLiuBaseline()
    out["labmt"] = LabMTBaseline()
    if include_legacy and legacy_path and os.path.exists(legacy_path):
        import json as _json
        with open(legacy_path, encoding="utf-8") as f:
            L = _json.load(f)
        out["V1_vader_toy"] = LegacyToy("V1_vader_toy", "vader", L["_VADER_SEEDS"])
        out["V1_nrc_toy"] = LegacyToy("V1_nrc_toy", "nrc", L["_NRC_SEEDS"])
        out["V1_liwc_toy"] = LegacyToy("V1_liwc_toy", "liwc", L["_LIWC_CATEGORIES"])
    return out
