# -*- coding: utf-8 -*-
"""
PLEF V2 -- standard-library purity harness.
AUTOGENERATED by scripts/02_baseline_environment.py.

Script 04 uses this to PROVE the PLEF core imports with no third-party package
available.

DESIGN NOTE -- why this runs in a subprocess:
An earlier design installed the blocker in the current process and purged
sys.modules of the blocked packages. That is unsafe. Compiled extension
modules such as numpy raise "ImportError: cannot load module more than once
per process" when removed and re-imported, which poisons the interpreter for
everything that runs afterwards. A purity claim must be tested in a process
that never imported the package in the first place, so the check is always
run in a fresh subprocess.
"""
import builtins
import json
import subprocess
import sys

BLOCKED_DEFAULT = ("numpy", "scipy", "pandas", "matplotlib", "sklearn",
                   "nltk", "torch", "empath", "afinn", "vaderSentiment",
                   "labMTsimple", "seaborn", "statsmodels")

_CHILD = r"""
import sys, json, builtins
blocked = set(json.loads(sys.argv[1]))
target  = sys.argv[2]
for extra in json.loads(sys.argv[3]):
    sys.path.insert(0, extra)
_orig = builtins.__import__
def _guard(name, *a, **kw):
    top = name.split('.')[0]
    if top in blocked:
        raise ImportError("PURITY VIOLATION: attempted import of '%s' "
                          "(blocked package '%s')" % (name, top))
    return _orig(name, *a, **kw)
builtins.__import__ = _guard
try:
    __import__(target)
    print(json.dumps({"ok": True, "error": None}))
except Exception as e:
    print(json.dumps({"ok": False, "error": "%s: %s" % (type(e).__name__, e)}))
"""


def assert_pure(module_name, blocked=BLOCKED_DEFAULT, extra_paths=()):
    """Import module_name in a FRESH subprocess with blocked packages
    unavailable. Returns (ok, error_string_or_None)."""
    try:
        r = subprocess.run(
            [sys.executable, "-c", _CHILD, json.dumps(list(blocked)),
             module_name, json.dumps([str(p) for p in extra_paths])],
            capture_output=True, text=True, timeout=180)
        out = (r.stdout or "").strip().splitlines()
        if not out:
            return False, "no output from purity subprocess: " + (r.stderr or "")[:300]
        d = json.loads(out[-1])
        return bool(d["ok"]), d["error"]
    except Exception as e:
        return False, "%s: %s" % (type(e).__name__, e)


class ImportBlocker:
    """In-process blocker. Use ONLY in a process that has not yet imported any
    blocked package. Prefer assert_pure(), which is subprocess-isolated."""
    def __init__(self, blocked=BLOCKED_DEFAULT):
        self.blocked = tuple(blocked)
        self._orig = None
        self.violations = []

    def _guard(self, name, *a, **kw):
        top = name.split(".")[0]
        if top in self.blocked:
            self.violations.append(name)
            raise ImportError("PURITY VIOLATION: attempted import of '%s' "
                              "(blocked package '%s')" % (name, top))
        return self._orig(name, *a, **kw)

    def __enter__(self):
        self._orig = builtins.__import__
        builtins.__import__ = self._guard
        return self

    def __exit__(self, *exc):
        builtins.__import__ = self._orig
        return False
